use serde::Serialize; use crate::ast::{BinaryOperator, Expression, Program, Statement};
#[derive(Debug, Clone, Serialize)] pub struct IrModule { pub functions: Vec<IrFunction> }
#[derive(Debug, Clone, Serialize)] pub struct IrFunction { pub name: String, pub instructions: Vec<Instruction> }
#[derive(Debug, Clone, Serialize)] pub enum Operand { Constant(i64), Temporary(String) }
#[derive(Debug, Clone, Serialize)] pub enum Instruction { Constant { destination: String, value: i64 }, Binary { destination: String, operator: String, left: Operand, right: Operand }, Store { name: String, value: Operand }, Return { value: Operand } }
pub fn lower(program: &Program) -> IrModule { IrModule { functions: program.functions.iter().map(lower_function).collect() } }
fn lower_function(function: &crate::ast::Function) -> IrFunction { let mut context = LoweringContext { next_temp: 0, instructions: Vec::new() }; for statement in &function.body { lower_statement(statement, &mut context); } IrFunction { name: function.name.clone(), instructions: context.instructions } }
struct LoweringContext { next_temp: usize, instructions: Vec<Instruction> } impl LoweringContext { fn temp(&mut self) -> String { let name = format!("%t{}", self.next_temp); self.next_temp += 1; name } }
fn lower_statement(statement: &Statement, context: &mut LoweringContext) { match statement { Statement::Let { name, value, .. } => { let value = lower_expression(value, context); context.instructions.push(Instruction::Store { name: name.clone(), value }); }, Statement::Return(value) => { let value = lower_expression(value, context); context.instructions.push(Instruction::Return { value }); }, Statement::If { then_branch, else_branch, .. } => { for statement in then_branch.iter().chain(else_branch.iter()) { lower_statement(statement, context); } }, Statement::Loop { body, .. } => { for statement in body { lower_statement(statement, context); } }, Statement::Expression(value) => { lower_expression(value, context); } } }
fn lower_expression(expression: &Expression, context: &mut LoweringContext) -> Operand { match expression { Expression::Integer(value) => Operand::Constant(*value), Expression::Identifier(name) => Operand::Temporary(format!("@{name}")), Expression::Binary { operator, left, right } => { let destination = context.temp(); let left = lower_expression(left, context); let right = lower_expression(right, context); let operator = match operator { BinaryOperator::Add => "add", BinaryOperator::Subtract => "sub", BinaryOperator::Multiply => "mul", BinaryOperator::Divide => "div", BinaryOperator::Greater => "gt", BinaryOperator::Less => "lt", BinaryOperator::Equal => "eq" }.into(); context.instructions.push(Instruction::Binary { destination: destination.clone(), operator, left, right }); Operand::Temporary(destination) }, _ => Operand::Constant(0) } }
