use crate::{ast::{BinaryOperator, Expression, Function, Program, Statement, TypeRef}, lexer::{Token, TokenKind}, semantic::Diagnostic};
pub fn parse(tokens: Vec<Token>) -> Result<Program, Vec<Diagnostic>> { let mut parser = Parser { tokens, current: 0, diagnostics: Vec::new() }; let mut functions = Vec::new(); while !parser.is_at_end() { if parser.matches(&TokenKind::Fn) { functions.push(parser.function()); } else { parser.error_current("Expected `fn` at the top level."); parser.advance(); } } if parser.diagnostics.is_empty() { Ok(Program { functions }) } else { Err(parser.diagnostics) } }
struct Parser { tokens: Vec<Token>, current: usize, diagnostics: Vec<Diagnostic> }
impl Parser {
 fn function(&mut self) -> Function { let name = self.consume_identifier("Expected function name after `fn`."); self.consume(&TokenKind::LeftParen, "Expected `(` after function name."); self.consume(&TokenKind::RightParen, "This prototype accepts zero-argument functions; expected `)`."); self.consume(&TokenKind::Arrow, "Expected `->` before the return type."); let return_type = self.parse_type(); self.consume(&TokenKind::LeftBrace, "Expected `{` to begin function body."); let body = self.block(); Function { name, return_type, body } }
 fn block(&mut self) -> Vec<Statement> { let mut statements = Vec::new(); while !self.check(&TokenKind::RightBrace) && !self.is_at_end() { statements.push(self.statement()); } self.consume(&TokenKind::RightBrace, "Expected `}` after block."); statements }
 fn statement(&mut self) -> Statement { if self.matches(&TokenKind::Let) { return self.let_statement(); } if self.matches(&TokenKind::Return) { let value = self.expression(); self.consume(&TokenKind::Semicolon, "Expected `;` after return value."); return Statement::Return(value); } if self.matches(&TokenKind::If) { return self.if_statement(); } if self.matches(&TokenKind::For) { return self.loop_statement(); } let value = self.expression(); self.consume(&TokenKind::Semicolon, "Expected `;` after expression."); Statement::Expression(value) }
 fn let_statement(&mut self) -> Statement { let name = self.consume_identifier("Expected variable name after `let`."); self.consume(&TokenKind::Colon, "Craft requires a static type after a binding name."); let type_ref = self.parse_type(); self.consume(&TokenKind::Equal, "Expected `=` before initializer."); let value = self.expression(); self.consume(&TokenKind::Semicolon, "Expected `;` after local binding."); Statement::Let { name, type_ref, value } }
 fn if_statement(&mut self) -> Statement { let condition = self.expression(); self.consume(&TokenKind::LeftBrace, "Expected `{` after if condition."); let then_branch = self.block(); let else_branch = if self.matches(&TokenKind::Else) { self.consume(&TokenKind::LeftBrace, "Expected `{` after else."); self.block() } else { Vec::new() }; Statement::If { condition, then_branch, else_branch } }
 fn loop_statement(&mut self) -> Statement { let name = self.consume_identifier("Expected loop binding after `for`."); self.consume(&TokenKind::In, "Expected `in` after loop binding."); let start = self.expression(); self.consume(&TokenKind::DotDot, "Expected `..` in loop range."); let end = self.expression(); self.consume(&TokenKind::LeftBrace, "Expected `{` after loop range."); let body = self.block(); Statement::Loop { name, start, end, body } }
 fn expression(&mut self) -> Expression { self.binary(0) }
 fn binary(&mut self, min_precedence: u8) -> Expression { let mut left = self.primary(); loop { let (operator, precedence) = match self.peek().kind { TokenKind::Plus => (BinaryOperator::Add, 1), TokenKind::Minus => (BinaryOperator::Subtract, 1), TokenKind::Star => (BinaryOperator::Multiply, 2), TokenKind::Slash => (BinaryOperator::Divide, 2), TokenKind::Greater => (BinaryOperator::Greater, 0), TokenKind::Less => (BinaryOperator::Less, 0), TokenKind::EqualEqual => (BinaryOperator::Equal, 0), _ => break }; if precedence < min_precedence { break; } self.advance(); let right = self.binary(precedence + 1); left = Expression::Binary { operator, left: Box::new(left), right: Box::new(right) }; } left }
 fn primary(&mut self) -> Expression { let token = self.advance().clone(); match token.kind { TokenKind::Number => Expression::Integer(token.lexeme.parse().unwrap_or(0)), TokenKind::True => Expression::Bool(true), TokenKind::False => Expression::Bool(false), TokenKind::String => Expression::String(token.lexeme.trim_matches('"').to_owned()), TokenKind::Identifier => Expression::Identifier(token.lexeme), TokenKind::LeftParen => { let value = self.expression(); self.consume(&TokenKind::RightParen, "Expected `)` after expression."); value }, TokenKind::LeftBracket => { let mut values = Vec::new(); if !self.check(&TokenKind::RightBracket) { loop { values.push(self.expression()); if !self.matches(&TokenKind::Comma) { break; } } } self.consume(&TokenKind::RightBracket, "Expected `]` after array elements."); Expression::Array(values) }, _ => { self.error(&token, "Expected an expression."); Expression::Integer(0) } } }
 fn parse_type(&mut self) -> TypeRef { if self.matches(&TokenKind::I32) { return TypeRef::I32; } if self.matches(&TokenKind::Bool) { return TypeRef::Bool; } if self.matches(&TokenKind::StringType) { return TypeRef::String; } if self.matches(&TokenKind::LeftBracket) { let inner = self.parse_type(); self.consume(&TokenKind::RightBracket, "Expected `]` after array element type."); return TypeRef::Array(Box::new(inner)); } self.error_current("Expected a static type such as `i32`, `bool`, or `[i32]`."); TypeRef::Unit }
 fn consume_identifier(&mut self, message: &str) -> String { if self.check(&TokenKind::Identifier) { return self.advance().lexeme.clone(); } self.error_current(message); "<error>".to_owned() } fn consume(&mut self, kind: &TokenKind, message: &str) { if self.check(kind) { self.advance(); } else { self.error_current(message); } } fn matches(&mut self, kind: &TokenKind) -> bool { if self.check(kind) { self.advance(); true } else { false } } fn check(&self, kind: &TokenKind) -> bool { std::mem::discriminant(&self.peek().kind) == std::mem::discriminant(kind) } fn advance(&mut self) -> &Token { if !self.is_at_end() { self.current += 1; } self.previous() } fn is_at_end(&self) -> bool { self.peek().kind == TokenKind::Eof } fn peek(&self) -> &Token { &self.tokens[self.current] } fn previous(&self) -> &Token { &self.tokens[self.current.saturating_sub(1)] } fn error_current(&mut self, message: &str) { let token = self.peek().clone(); self.error(&token, message); } fn error(&mut self, token: &Token, message: &str) { self.diagnostics.push(Diagnostic::error(message, token.line, token.column)); }
}
