use serde::Serialize; use std::collections::HashMap; use crate::ast::{Expression, Program, Statement, TypeRef};
#[derive(Debug, Clone, Serialize)] pub struct Diagnostic { pub severity: String, pub message: String, pub line: usize, pub column: usize, pub note: Option<String> }
impl Diagnostic { pub fn error(message: &str, line: usize, column: usize) -> Self { Self { severity: "error".into(), message: message.into(), line, column, note: Some("The compiler stopped this stage because the program shape is ambiguous or invalid.".into()) } } pub fn is_error(&self) -> bool { self.severity == "error" } }
#[derive(Debug, Clone, Serialize)] pub struct Symbol { pub name: String, pub type_name: String, pub scope: String, pub role: String }
#[derive(Debug, Clone, Serialize)] pub struct SemanticArtifacts { pub symbols: Vec<Symbol>, pub diagnostics: Vec<Diagnostic> }
pub fn analyze(program: &Program) -> SemanticArtifacts { let mut symbols = Vec::new(); let mut diagnostics = Vec::new(); for function in &program.functions { symbols.push(Symbol { name: function.name.clone(), type_name: format!("fn() -> {}", display_type(&function.return_type)), scope: "module".into(), role: "function".into() }); let mut locals = HashMap::new(); for statement in &function.body { inspect_statement(statement, &function.name, &mut locals, &mut symbols, &mut diagnostics); } } SemanticArtifacts { symbols, diagnostics } }
fn inspect_statement(statement: &Statement, scope: &str, locals: &mut HashMap<String, TypeRef>, symbols: &mut Vec<Symbol>, diagnostics: &mut Vec<Diagnostic>) { match statement { Statement::Let { name, type_ref, value } => { let actual = infer(value, locals, diagnostics); if &actual != type_ref && actual != TypeRef::Unit { diagnostics.push(Diagnostic::error(&format!("Type mismatch: `{name}` is declared as {}, but its initializer is {}.", display_type(type_ref), display_type(&actual)), 0, 0)); } locals.insert(name.clone(), type_ref.clone()); symbols.push(Symbol { name: name.clone(), type_name: display_type(type_ref), scope: scope.into(), role: "local binding".into() }); }, Statement::Return(value) | Statement::Expression(value) => { infer(value, locals, diagnostics); }, Statement::If { condition, then_branch, else_branch } => { infer(condition, locals, diagnostics); for value in then_branch.iter().chain(else_branch.iter()) { inspect_statement(value, scope, locals, symbols, diagnostics); } }, Statement::Loop { name, start, end, body } => { infer(start, locals, diagnostics); infer(end, locals, diagnostics); locals.insert(name.clone(), TypeRef::I32); symbols.push(Symbol { name: name.clone(), type_name: "i32".into(), scope: scope.into(), role: "loop binding".into() }); for value in body { inspect_statement(value, scope, locals, symbols, diagnostics); } } } }
fn infer(expression: &Expression, locals: &HashMap<String, TypeRef>, diagnostics: &mut Vec<Diagnostic>) -> TypeRef { match expression { Expression::Integer(_) => TypeRef::I32, Expression::Bool(_) => TypeRef::Bool, Expression::String(_) => TypeRef::String, Expression::Identifier(name) => locals.get(name).cloned().unwrap_or_else(|| { diagnostics.push(Diagnostic::error(&format!("Unknown identifier `{name}`."), 0, 0)); TypeRef::Unit }), Expression::Array(values) => { let inner = values.first().map(|value| infer(value, locals, diagnostics)).unwrap_or(TypeRef::Unit); TypeRef::Array(Box::new(inner)) }, Expression::Call { callee, arguments } => { for argument in arguments { infer(argument, locals, diagnostics); } if matches!(callee.as_ref(), Expression::Identifier(name) if name == "print") { TypeRef::Unit } else { diagnostics.push(Diagnostic::error("Only the built-in `print` call is available in this runtime prototype.", 0, 0)); TypeRef::Unit } }, Expression::Index { target, index } => { let target_type = infer(target, locals, diagnostics); let index_type = infer(index, locals, diagnostics); if index_type != TypeRef::I32 { diagnostics.push(Diagnostic::error("Array indices must be i32 values.", 0, 0)); } if let TypeRef::Array(inner) = target_type { *inner } else { diagnostics.push(Diagnostic::error("Indexing requires an array value.", 0, 0)); TypeRef::Unit } }, Expression::Binary { left, right, .. } => { let left = infer(left, locals, diagnostics); let right = infer(right, locals, diagnostics); if left != right { diagnostics.push(Diagnostic::error("Binary operands must have the same static type.", 0, 0)); TypeRef::Unit } else { left } } } }
pub fn display_type(type_ref: &TypeRef) -> String { match type_ref { TypeRef::I32 => "i32".into(), TypeRef::Bool => "bool".into(), TypeRef::String => "string".into(), TypeRef::Array(inner) => format!("[{}]", display_type(inner)), TypeRef::Unit => "unit".into() } }
